export default {
    SAY: 'SAY',

    SET_AUTHENTICATED: 'SET_AUTHENTICATED',
    SET_DEAUTHENTICATED: 'SET_DEAUTHENTICATED',

    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',

    DISPLAY_NOTIFICATION: 'DISPLAY_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
};
