export default {
    SAY: 'SAY',

    START_LOADING: 'START_LOADING',
    STOP_LOADING: 'STOP_LOADING',

    DISPLAY_NOTIFICATION: 'DISPLAY_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
};
